namespace HeroQuest.Domain
{
    public enum GameErrorCode
    {
        Success = 0,
        InternalError = 1,
        InvalidParameter = 2,
        NotLoggedIn = 3,
        TooFrequent = 4,
        InvalidToken = 100,
        AccountBanned = 101,
        CharacterNameExists = 102,
        InvalidClass = 103,
        InvalidLayer = 200,
        LayerLocked = 201,
        NotInDungeon = 202,
        TargetNotFound = 300,
        TargetDead = 301,
        SkillNotFound = 302,
        SkillInCooldown = 303,
        SelfDead = 304,
        ResourceCollected = 305,
        EmptySlot = 400,
        InvalidSlot = 401,
        MaterialNotEnough = 405,
        StrengthenFailed = 406,
        NotHostileTarget = 500,
        TargetInvincible = 501,
        SelfIsRedName = 502,
        PetNotFound = 600,
        PetExploring = 603,
        PetSynthesizeMaterialCountInvalid = 604,
        PetSynthesizeQualityMismatch = 605,
        TradeOrderNotFound = 700,
        GoodsSold = 701,
        CannotBuyOwnGoods = 702,
        ShopGoodsNotFound = 800,
        StockNotEnough = 801,
        LevelNotEnough = 802,
        GoldNotEnough = 900,
        HonorNotEnough = 901,
        AttributePointNotEnough = 902,
        SkillPointNotEnough = 903,
        SkillMaxLevel = 904
    }
}
